### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by mrrhysbutler** [SriApps/Test#1]
Build task executes correctly. When running on device, Run Build fails with error: 

> Cause: java.lang.NullPointerException

 at **:app:transformClassesWithInstantRunForDebug**

### Environment
Android Studio 3.1.2
Gradle 4.5.1
Devices: Tried Galaxy S5, 6.0.1, Simulator (Nexus 5X API 27)

See [attached log](https://github.com/SriApps/Test/files/1965924/log.txt) for output.

**Comment by SriApps** [comment]
I have changed project environment to mirror your Environment.
Android Studio  3.1.2
Gradle 4.5.1
Android plugin Version is 3.1.2 
It looks like APK was not installed on any of the device because of the run build error. I have tested in various devices including (Nexus 5X API 26 and Pixel XL API 27).

**Comment by mrrhysbutler** [comment]
Issue resolved with latest update
